import { useAppState } from '../hooks/useAppState';
import { KPICard, EmptyState, PageHeader } from '../components/common';
import { Monitor, ShieldCheck, ShieldAlert, ShieldX, Wifi, WifiOff, Bug, Cpu, ScanLine, HardDrive, Settings, Upload } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { formatDate } from '../utils/dateUtils';
import { formatNumber } from '../utils/formatUtils';

export default function DashboardPage() {
  const state = useAppState();
  const navigate = useNavigate();
  const kpi = state.kpiSummary;
  const cats = state.categoryStats;
  if (!state.assessmentRun || !kpi) return <div><PageHeader title="Dashboard" description="Endpoint Security Daily Health Overview" /><EmptyState icon={Upload} title="No Assessment Data" description="Upload Intune and MDE reports from the Data Import page to view the health dashboard." action={<button onClick={() => navigate('/import')} className="btn-primary">Go to Data Import</button>} /></div>;

  const avgScore = state.mergedDevices.length > 0 ? Math.round(state.mergedDevices.reduce((sum, device) => sum + device.healthScore, 0) / state.mergedDevices.length) : 0;
  const totalHealth = Math.max(1, kpi.healthyDevices + kpi.warningDevices + kpi.criticalDevices);
  const healthRows = [
    { label: 'Healthy', value: kpi.healthyDevices, color: 'bg-emerald-500' },
    { label: 'Warning', value: kpi.warningDevices, color: 'bg-amber-500' },
    { label: 'Critical', value: kpi.criticalDevices, color: 'bg-red-500' },
  ];

  return <div>
    <PageHeader title="Dashboard" description={`Assessment run on ${formatDate(state.assessmentDate)}`} actions={<button onClick={() => navigate('/import')} className="btn-secondary text-sm">New Assessment</button>} />
    <div className="glass-card p-6 mb-8 border-l-4 border-l-primary-500"><h2 className="text-lg font-bold text-surface-100 mb-3">Daily Endpoint Security Health Summary</h2><div className="space-y-1 text-sm text-surface-400"><p><span className="text-surface-200 font-semibold">{formatNumber(kpi.totalIntuneDevices)}</span> total endpoints reported by Intune.</p><p><span className="text-surface-200 font-semibold">{formatNumber(kpi.devicesInScope)}</span> endpoints are in scope based on the selected reporting window.</p><p><span className="text-emerald-400 font-semibold">{formatNumber(kpi.mdeMatched)}</span> endpoints successfully matched with MDE.</p>{kpi.mdeMissing > 0 && <p><span className="text-red-400 font-semibold">{formatNumber(kpi.mdeMissing)}</span> endpoints have no corresponding MDE health record.</p>}<p><span className="text-emerald-400 font-semibold">{formatNumber(kpi.healthyDevices)}</span> healthy, <span className="text-amber-400 font-semibold">{formatNumber(kpi.warningDevices)}</span> require attention, <span className="text-red-400 font-semibold">{formatNumber(kpi.criticalDevices)}</span> critical.</p></div>{kpi.criticalDevices > 0 && <button onClick={() => navigate('/actions')} className="btn-danger mt-4 text-sm">View {kpi.criticalDevices} Critical Endpoint{kpi.criticalDevices !== 1 ? 's' : ''}</button>}</div>
    <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 gap-4 mb-8"><KPICard title="Devices In Scope" value={formatNumber(kpi.devicesInScope)} icon={Monitor} color="text-primary-400" /><KPICard title="MDE Matched" value={formatNumber(kpi.mdeMatched)} icon={ShieldCheck} color="text-emerald-400" /><KPICard title="MDE Missing" value={formatNumber(kpi.mdeMissing)} icon={WifiOff} color="text-red-400" /><KPICard title="Healthy" value={formatNumber(kpi.healthyDevices)} icon={ShieldCheck} color="text-emerald-400" /><KPICard title="Warning" value={formatNumber(kpi.warningDevices)} icon={ShieldAlert} color="text-amber-400" /><KPICard title="Critical" value={formatNumber(kpi.criticalDevices)} icon={ShieldX} color="text-red-400" /></div>
    <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-8"><KPICard title="Sensor Issues" value={kpi.sensorIssues} icon={Wifi} color="text-orange-400" /><KPICard title="Signature Issues" value={kpi.signatureIssues} icon={Bug} color="text-purple-400" /><KPICard title="Platform Issues" value={kpi.platformIssues} icon={Cpu} color="text-cyan-400" /><KPICard title="Quick Scan Issues" value={kpi.quickScanIssues} icon={ScanLine} color="text-pink-400" /><KPICard title="Full Scan Issues" value={kpi.fullScanIssues} icon={HardDrive} color="text-teal-400" /><KPICard title="Config Issues" value={kpi.securityConfigIssues} icon={Settings} color="text-indigo-400" /></div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8"><div className="glass-card p-6"><h3 className="text-sm font-semibold text-surface-300 mb-4">Overall Health Distribution</h3>{healthRows.map(row => <div key={row.label} className="mb-4"><div className="flex justify-between text-sm text-surface-300 mb-1"><span>{row.label}</span><span>{formatNumber(row.value)}</span></div><div className="h-3 rounded-full bg-surface-800 overflow-hidden"><div className={`h-full ${row.color}`} style={{ width: `${(row.value / totalHealth) * 100}%` }} /></div></div>)}</div><div className="glass-card p-6"><h3 className="text-sm font-semibold text-surface-300 mb-4">Average Health Score</h3><div className="text-5xl font-bold text-primary-400">{avgScore}%</div><p className="mt-3 text-sm text-surface-400">Average across {formatNumber(state.mergedDevices.length)} assessed devices.</p></div><div className="glass-card p-6"><h3 className="text-sm font-semibold text-surface-300 mb-4">MDE Coverage</h3><div className="text-5xl font-bold text-emerald-400">{kpi.devicesInScope ? Math.round((kpi.mdeMatched / kpi.devicesInScope) * 100) : 0}%</div><p className="mt-3 text-sm text-surface-400">{formatNumber(kpi.mdeMatched)} matched and {formatNumber(kpi.mdeMissing)} missing from MDE.</p></div></div>
    <div className="glass-card p-6"><h3 className="text-sm font-semibold text-surface-300 mb-4">Issues by Category</h3><div className="space-y-4">{cats.map(category => <div key={category.category}><div className="flex justify-between text-sm text-surface-300 mb-1"><span>{category.category}</span><span>{category.critical} critical · {category.warning} warning · {category.healthy} healthy</span></div><div className="flex h-3 overflow-hidden rounded-full bg-surface-800"><div className="bg-emerald-500" style={{ width: `${category.total ? (category.healthy / category.total) * 100 : 0}%` }} /><div className="bg-amber-500" style={{ width: `${category.total ? (category.warning / category.total) * 100 : 0}%` }} /><div className="bg-red-500" style={{ width: `${category.total ? (category.critical / category.total) * 100 : 0}%` }} /></div></div>)}</div></div>
  </div>;
}
